# Generated by Django 5.0.1 on 2024-01-25 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contas',
            fields=[
                ('username', models.TextField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('foto_perfil', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('comentario', models.TextField(max_length=400)),
                ('data_postagem', models.DateTimeField(default=datetime.datetime.now)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
