# Generated by Django 5.0.1 on 2024-01-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas',
            name='email',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
