# Generated by Django 5.0.1 on 2024-01-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0002_contas_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contas',
        ),
    ]
