# Generated by Django 5.0.1 on 2024-01-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
