# Generated by Django 5.0.1 on 2024-01-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0007_postagem_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
