# Generated by Django 5.0.1 on 2024-01-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0008_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='usuario',
        ),
        migrations.AddField(
            model_name='postagem',
            name='numero_usuario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
