# Generated by Django 5.0.1 on 2024-01-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0010_remove_postagem_numero_usuario_postagem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='user',
        ),
        migrations.AddField(
            model_name='postagem',
            name='numero_usuario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
