# Generated by Django 5.0.1 on 2024-01-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0012_remove_postagem_numero_usuario_postagem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='comentario',
            field=models.TextField(max_length=401),
        ),
    ]
