# Generated by Django 5.0.1 on 2024-01-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0013_alter_postagem_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='comentario',
            field=models.TextField(max_length=400),
        ),
    ]
