# Generated by Django 5.0.1 on 2024-01-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0014_alter_postagem_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('imdb_rating', models.FloatField()),
                ('released_year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('poster_link', models.URLField()),
            ],
        ),
    ]
