# Generated by Django 5.0.1 on 2024-01-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0015_filme'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='Runtime',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
