# Generated by Django 5.0.1 on 2024-01-31 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0016_filme_runtime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filme',
        ),
        migrations.AddField(
            model_name='postagem',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='postagem_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
