# Generated by Django 5.0.1 on 2024-02-05 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0017_delete_filme_postagem_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series_Title', models.CharField(max_length=50)),
                ('Released_Year', models.IntegerField()),
                ('Runtime', models.CharField(max_length=10)),
                ('Genre', models.CharField(max_length=50)),
                ('Rating', models.FloatField()),
                ('Overview', models.TextField(max_length=400)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
