# Generated by Django 5.0.1 on 2024-02-06 19:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0021_postagem_comentarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='comentarios',
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, max_length=400, null=True)),
                ('data_comentario', models.DateField(default=datetime.datetime.now)),
                ('comentario_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_filhos', to='Movied.comentarios')),
                ('postagem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_postagem', to='Movied.postagem')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comentarios_postagem_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
