# Generated by Django 5.0.1 on 2024-02-06 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0022_remove_postagem_comentarios_comentarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comentario_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
