# Generated by Django 5.0.1 on 2024-02-06 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0023_comentarios_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='data_comentario',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
