# Generated by Django 5.0.1 on 2024-02-07 09:24

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0024_alter_comentarios_data_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='reported',
            field=models.BooleanField(blank=True, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
