# Generated by Django 5.0.1 on 2024-02-07 09:28

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0025_postagem_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='reported',
            field=models.BooleanField(default=False, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='reported',
            field=models.BooleanField(default=False, verbose_name=django.contrib.auth.models.User),
        ),
    ]
