# Generated by Django 5.0.1 on 2024-02-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0026_comentarios_reported_alter_postagem_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
