# Generated by Django 5.0.1 on 2024-02-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0027_alter_postagem_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='comentario_pai',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='likes',
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
