# Generated by Django 5.0.1 on 2024-02-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0028_remove_comentarios_comentario_pai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poster_Link', models.URLField()),
                ('Series_Title', models.CharField(max_length=50)),
                ('Released_Year', models.IntegerField()),
                ('Runtime', models.CharField(max_length=10)),
                ('Genre', models.CharField(max_length=50)),
                ('Rating', models.FloatField()),
                ('Overview', models.TextField(max_length=400)),
            ],
        ),
    ]
