# Generated by Django 5.0.1 on 2024-02-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0029_filmes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='Released_Year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
