# Generated by Django 5.0.1 on 2024-02-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0030_alter_filmes_released_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
