# Generated by Django 5.0.1 on 2024-02-09 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0031_alter_comentarios_id_alter_filmes_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='filmes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filmes', to='Movied.filmes'),
        ),
    ]
