# Generated by Django 5.0.1 on 2024-02-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0033_remove_postagem_filmes_filmes_postagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='postagens',
        ),
        migrations.AddField(
            model_name='postagem',
            name='filmes',
            field=models.ManyToManyField(blank=True, related_name='postagens', to='Movied.filmes'),
        ),
    ]
