# Generated by Django 5.0.1 on 2024-02-15 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0034_remove_filmes_postagens_postagem_filmes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='Streaming',
            field=models.URLField(blank=True, null=True),
        ),
    ]
