# Generated by Django 5.0.1 on 2024-02-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0037_notification_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LK', 'Like'), ('FL', 'Follow')], default='Like', max_length=2),
        ),
    ]
