# Generated by Django 5.0.1 on 2024-02-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0038_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LK', 'Like'), ('FL', 'Follow'), ('CM', 'Comment')], default='Like', max_length=20),
        ),
    ]
