# Generated by Django 5.0.1 on 2024-02-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0041_alter_suggestions_series_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='Series_Title',
            field=models.CharField(max_length=110),
        ),
    ]
