# Generated by Django 5.0.1 on 2024-03-11 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0047_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='list',
            field=models.ManyToManyField(blank=True, related_name='postagem_listed', to=settings.AUTH_USER_MODEL),
        ),
    ]
