# Generated by Django 5.0.1 on 2024-03-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0048_postagem_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
