# Generated by Django 5.0.1 on 2024-03-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movied', '0049_notification_isread'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
